plugins {
    id 'com.android.application'
}

android {
    namespace 'com.viferor.radioespana'
    compileSdk 34

    defaultConfig {
        applicationId 'com.viferor.radioespana'
        minSdk 23
        targetSdk 34
        versionCode 11010
        versionName '1.10.1'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
