plugins {
    id 'com.android.application'
}

android {
    namespace 'com.viferor.radioespana'
    compileSdk 34

    defaultConfig {
        applicationId 'com.viferor.radioespana'
        minSdk 23
        targetSdk 34
        versionCode 11400
        versionName '1.14.0'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
