import zlib from 'node:zlib';
const EPG_URLS=['https://www.tdtchannels.com/epg/RADIO.xml.gz','https://www.tdtchannels.com/epg/RADIO.xml'];
let cache={at:0,programmes:[]};
function clean(v){return String(v??'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();}
function parseDate(v){const s=String(v||'').trim();if(!s)return NaN;const m=s.match(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})(?:\s*([+-]\d{4}))?/);if(!m)return Date.parse(s);const iso=`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}${m[7]?m[7].slice(0,3)+':'+m[7].slice(3):'Z'}`;return Date.parse(iso);}
function parseXml(xml){const out=[];const re=/<programme\b([^>]*)>([\s\S]*?)<\/programme>/gi;let m;while((m=re.exec(xml))){const a=m[1],body=m[2];const channel=(a.match(/\bchannel=["']([^"']+)["']/i)||[])[1]||'';const start=(a.match(/\bstart=["']([^"']+)["']/i)||[])[1]||'';const stop=(a.match(/\bstop=["']([^"']+)["']/i)||[])[1]||'';const title=(body.match(/<title(?:\s[^>]*)?>([\s\S]*?)<\/title>/i)||[])[1]||'';const desc=(body.match(/<desc(?:\s[^>]*)?>([\s\S]*?)<\/desc>/i)||[])[1]||'';if(title&&channel)out.push({channel:clean(channel),title:clean(title),description:clean(desc),start:parseDate(start),end:parseDate(stop)});}return out;}
async function fetchText(url){const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),10000);try{const r=await fetch(url,{signal:ctl.signal,headers:{'User-Agent':'RadioEspana/1.2.1','Accept':'application/xml,application/gzip,text/xml'}});if(!r.ok)throw Error('EPG HTTP '+r.status);const ab=await r.arrayBuffer();let b=Buffer.from(ab);if(/\.gz(?:\?|$)/i.test(url)||String(r.headers.get('content-encoding')||'').includes('gzip')){try{b=zlib.gunzipSync(b);}catch{}}return b.toString('utf8');}finally{clearTimeout(t);}}
async function load(){if(cache.programmes.length&&Date.now()-cache.at<300000)return cache.programmes;let last;for(const u of EPG_URLS){try{const xml=await fetchText(u);const p=parseXml(xml);if(p.length>100){cache={at:Date.now(),programmes:p};return p;}}catch(e){last=e;}}throw last||Error('EPG unavailable');}
function same(a,b){const x=String(a||'').trim().toLowerCase(),y=String(b||'').trim().toLowerCase();return x===y||x.replace(/\.radio$/,'')===y.replace(/\.radio$/,'');}
export default async function handler(req,res){try{const epg=String(req.query?.epg_id||'').trim(),name=String(req.query?.name||'').trim();if(!epg&&!name)return res.status(400).json({error:'Falta epg_id o name'});const all=await load(),now=Date.now();let relevant=all.filter(x=>epg?same(x.channel,epg):same(x.channel,name));if(!relevant.length&&epg){const short=epg.replace(/\.radio$/i,'');relevant=all.filter(x=>same(x.channel,short)||String(x.channel).toLowerCase().includes(short.toLowerCase()));}const current=relevant.filter(x=>x.start<=now&&x.end>=now).sort((a,b)=>b.start-a.start)[0]||null;const next=relevant.filter(x=>x.start>now).sort((a,b)=>a.start-b.start)[0]||null;res.setHeader('Cache-Control','s-maxage=60, stale-while-revalidate=300');return res.status(200).json({current,next,source:'tdtchannels-epg'});}catch(e){return res.status(200).json({current:null,next:null,error:e.message||'epg_unavailable'});}}
